# Generated by Django 6.0.1 on 2026-01-29 09:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the study plan', max_length=200)),
                ('exam_date', models.DateField(help_text='Target exam date')),
                ('daily_study_hours', models.DecimalField(decimal_places=2, default=4.0, help_text='Hours available for study per day', max_digits=4)),
                ('start_date', models.DateField(default=django.utils.timezone.now, help_text='When to start studying')),
                ('is_active', models.BooleanField(default=True, help_text='Is this plan currently active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('total_days_available', models.IntegerField(default=0, help_text='Total days between start and exam')),
                ('total_hours_available', models.DecimalField(decimal_places=2, default=0, help_text='Total study hours available', max_digits=10)),
                ('user', models.ForeignKey(help_text='The student who owns this plan', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Study Plan',
                'verbose_name_plural': 'Study Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date for this schedule')),
                ('total_hours_planned', models.DecimalField(decimal_places=2, default=0, help_text='Total hours planned for this day', max_digits=5)),
                ('is_completed', models.BooleanField(default=False, help_text="Has this day's schedule been completed?")),
                ('notes', models.TextField(blank=True, help_text='Notes for this day')),
                ('study_plan', models.ForeignKey(help_text='Study plan this schedule belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='daily_schedules', to='planner.studyplan')),
            ],
            options={
                'verbose_name': 'Daily Schedule',
                'verbose_name_plural': 'Daily Schedules',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Subject name (e.g., 'Anatomy', 'Physiology')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description of the subject', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this subject was created')),
                ('total_topics', models.IntegerField(default=0, help_text='Total number of topics in this subject')),
                ('completed_topics', models.IntegerField(default=0, help_text='Number of completed topics')),
                ('user', models.ForeignKey(help_text='The student who owns this subject', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='studyplan',
            name='subject',
            field=models.ForeignKey(help_text='Subject this plan covers', on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to='planner.subject'),
        ),
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the document', max_length=300)),
                ('pdf_file', models.FileField(help_text='The actual PDF file', upload_to='pdfs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='When the PDF was uploaded')),
                ('extracted_text', models.TextField(blank=True, help_text='Full text extracted from PDF')),
                ('extracted_structure', models.JSONField(blank=True, default=dict, help_text='Structured data extracted from PDF (chapters, topics, etc.)')),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of PDF processing', max_length=20)),
                ('page_count', models.IntegerField(default=0, help_text='Number of pages in the PDF')),
                ('user', models.ForeignKey(help_text='The student who uploaded this PDF', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, help_text='Subject this PDF belongs to (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='planner.subject')),
            ],
            options={
                'verbose_name': 'PDF Document',
                'verbose_name_plural': 'PDF Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Topic name/title', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Details about the topic')),
                ('importance', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', help_text='How important is this topic', max_length=10)),
                ('is_exam_critical', models.BooleanField(default=False, help_text='Is this topic frequently asked in exams?')),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=2.0, help_text='Estimated time to complete (hours)', max_digits=5)),
                ('order', models.IntegerField(default=0, help_text='Order in which topics should be studied')),
                ('is_completed', models.BooleanField(default=False, help_text='Has this topic been completed?')),
                ('completion_date', models.DateField(blank=True, help_text='When was this topic completed', null=True)),
                ('notes', models.TextField(blank=True, help_text="Student's personal notes on this topic")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_source', models.ForeignKey(blank=True, help_text='PDF this topic was extracted from (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='planner.pdfdocument')),
                ('subject', models.ForeignKey(help_text='Subject this topic belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='planner.subject')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_hours', models.DecimalField(decimal_places=2, help_text='Hours allocated for this topic on this day', max_digits=5)),
                ('order', models.IntegerField(default=0, help_text='Order in which to study topics')),
                ('is_completed', models.BooleanField(default=False, help_text='Has this been completed?')),
                ('daily_schedule', models.ForeignKey(help_text='Daily schedule', on_delete=django.db.models.deletion.CASCADE, to='planner.dailyschedule')),
                ('topic', models.ForeignKey(help_text='Topic to study', on_delete=django.db.models.deletion.CASCADE, to='planner.topic')),
            ],
            options={
                'verbose_name': 'Scheduled Topic',
                'verbose_name_plural': 'Scheduled Topics',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RevisionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(help_text='When this revision is scheduled')),
                ('revision_number', models.IntegerField(help_text='Which revision is this (1, 2, or 3)')),
                ('is_completed', models.BooleanField(default=False, help_text='Has this revision been completed?')),
                ('completed_date', models.DateField(blank=True, help_text='When was this revision completed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Revision notes')),
                ('topic', models.ForeignKey(help_text='Topic to revise', on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='planner.topic')),
            ],
            options={
                'verbose_name': 'Revision Task',
                'verbose_name_plural': 'Revision Tasks',
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.AddField(
            model_name='dailyschedule',
            name='topics',
            field=models.ManyToManyField(help_text='Topics scheduled for this day', through='planner.ScheduledTopic', to='planner.topic'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, help_text='Full name of the student', max_length=200)),
                ('institution', models.CharField(blank=True, help_text='College/Institution name', max_length=200)),
                ('course', models.CharField(blank=True, help_text='Course name (e.g., MBBS, B.Tech)', max_length=200)),
                ('default_daily_hours', models.DecimalField(decimal_places=2, default=4.0, help_text='Default daily study hours', max_digits=4)),
                ('timezone', models.CharField(default='Asia/Kolkata', help_text="User's timezone", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.AlterUniqueTogether(
            name='dailyschedule',
            unique_together={('study_plan', 'date')},
        ),
    ]
